MarMarWax/Models/ErrorViewModel.cs
using System;

namespace MarMarWax.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MarMarWax/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MarMarWax.Models;
using App.DomainServices.Repositories;
using App.DomainModels.ViewModels.ContactUs;
using App.Common.Extentions;
using App.Common.Toolkit;
using Microsoft.AspNetCore.Authorization;
using App.DomainServices.Identity;

namespace MarMarWax.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly ContactUsRepository _ContactUsRepository;
        public ContactUsController(ContactUsRepository ContactUsRepository)
        {
            _ContactUsRepository = ContactUsRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ContactUsViewModel vm)
        {
            var result = _ContactUsRepository.Create(vm);
            TempData.AddResult(result);
            return View(nameof(Index));
        }

        //public IActionResult Edit(int Id)
        //{
        //    var entity = _ContactUsRepository.GetById(Id);
        //    return View(entity);
        //}

        //[HttpPost]
        //public IActionResult Edit(ContactUsViewModel vm,int Id)
        //{
        //    var result = _ContactUsRepository.Edit(vm,Id);
        //    TempData.AddResult(result);
        //    return Utility.CloseAndRefresh();
        //}
        

    }
}

MarMarWax/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MarMarWax.Models;
using App.DomainServices.Repositories;

namespace MarMarWax.Controllers
{
    public class HomeController : Controller
    {
        private readonly ProductRepository _productRepository;
        private readonly BlogsRepository _blogsRepository;
        private readonly InfoRepository _infoRepository;
        public HomeController(ProductRepository productRepository, BlogsRepository blogsRepository, InfoRepository infoRepository)
        {
            _infoRepository = infoRepository;
            _blogsRepository = blogsRepository;
            _productRepository = productRepository;
        }
        public IActionResult Index()
        {
            ViewBag.ProductList = _productRepository.GetAll();
            ViewBag.BlogList = _blogsRepository.GetRandom();

            return View();
        }

        public IActionResult About()
        {
            var model = _infoRepository.Get();

            return View(model);
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MarMarWax/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MarMarWax.Models;
using App.DomainServices.Repositories;

namespace MarMarWax.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductRepository _productRepository;
        private readonly ProductColorRepository _productColorRepository;
        private readonly ProductTypeRepository _productTypeRepository;
        public ProductController(ProductRepository productRepository, ProductColorRepository productColorRepository, BlogsRepository blogsRepository, ProductTypeRepository productTypeRepository)
        {
            _productRepository = productRepository;
            _productColorRepository = productColorRepository;
            _productTypeRepository = productTypeRepository;
        }
        public IActionResult Index(int ProductTypeId)
        {
            var ProductList = _productRepository.GetAllWithProductTypeId(ProductTypeId);
            ViewBag.ProductTypes = _productTypeRepository.GetAll(null);
            return View(ProductList);
        }
          public IActionResult Getall()
        {
            var ProductList = _productRepository.GetAll();
            ViewBag.ProductTypes = _productTypeRepository.GetAll(null);
            return View(ProductList);
        }

        public IActionResult ProductDetail(int Id)
        {
            var Product= _productRepository.GetById(Id);
            Product.ProductGalleryImages.Add(new App.DomainModels.Dto.Product.ProductGalleryImageDTO {
                Image = Product.Image,
                ProductId = Id
            });
            ViewBag.colors = _productColorRepository.GetAll(Id);
            return View(Product);
        }

    }
}

MarMarWax/Views/ContactUs/Index.cshtml
@using App.DomainModels.SSOT
@inject FileConfig config
@{
    ViewData["Title"] = "ارتباط با ما";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Title Page -->
<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url(../../images/pic-1.jpg);height:300px">
    <h2 class="l-text2 t-center" style="color:black;font-family:'IRANSans'">
        ارتباط با ما
    </h2>
</section>

<!-- content page -->
<section class="bgwhite p-t-66 p-b-60">
    <div class="container">
        <div class="row">
            

            <div class="col-md-12 p-b-30" dir="rtl" style="color:black;font-family:'IRANSans'">
                <form asp-action="Create" asp-controller="ContactUs" method="post" class="leave-comment">
                    <h4 class="m-text26 p-b-36 p-t-15" style="color:black;font-family:'IRANSans'">
                        ارتباط با ما
                    </h4>

                    <div class="bo4 of-hidden size15 m-b-20">
                        <input class="sizefull s-text7 p-l-22 p-r-22" type="text" name="name" placeholder="نام و نام خانوادگی">
                    </div>

                    <div class="bo4 of-hidden size15 m-b-20">
                        <input class="sizefull s-text7 p-l-22 p-r-22" type="number" name="PhoneNumber" placeholder="شماره تماس">
                    </div>

                    <div class="bo4 of-hidden size15 m-b-20">
                        <input class="sizefull s-text7 p-l-22 p-r-22" type="email" name="email" placeholder="ایمیل">
                    </div>

                    <textarea class="dis-block s-text7 size20 bo4 p-l-22 p-r-22 p-t-13 m-b-20" name="Description" placeholder="پیام"></textarea>

                    <div class="w-size25 pull-left">
                        <!-- Button -->
                        <button class="flex-c-m size2 bg1 bo-rad-23 hov1 m-text3 trans-0-4">
                            ارسال
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

MarMarWax/Views/Shared/Components/MenuComponents/Menu.cshtml
@using App.DomainModels.Dto.Product
@{
    List<ProductTypeDTO> productTypes = ViewBag.productTypes;
}

<script>
    $(() => {
        console.log($('.hassubs'));
        $('.mainnav .hassubs').on('mouseover', function(e) {
            const width = $(this).outerWidth();
            const left = $(this).offset().left;
            $('.nav-item-hover').width(width);
            $('.nav-item-hover').css('left' , left + (width/2));
        }).on('mouseleave', function() {
            $('.nav-item-hover').width(0);
        })
    })
    
</script>
<style>
    
    /*General Menu Styling*/
    .main {
        height: 100%;
        width: 100%;
        position: relative;
        display: flex;
        justify-content: flex-start;
        direction: rtl;
    }
    .nav-item-hover {
        display: block;
        width: 0;
        height: 3px;
        background: #ba0000;
        position: absolute;
        bottom: 0;
        left: 0;
        -webkit-transform: translateX(-50%);
        transform: translateX(-50%);
        -webkit-transition: .5s;
        transition: .5s;
    }
    .mainnav {
        display: flex;
        justify-content: flex-start;
        align-items: center;
        height: 100%;
    }

    li {
        list-style: none;
    }

        li a {
            text-decoration: none;
            text-align:center;
        }
    .hassubs:hover .dropdown {
        opacity: 1;
        visibility: visible;
    }
    .dropdown {
        position: absolute;
        top: 100%;
        background-color: #fff;
        padding-right: 0;
        transition: ease-out .35s;
        -moz-transition: ease-out .35s;
        -webkit-transition: ease-out .35s;
        border-bottom: 2px solid #ba0000;
        width: 100%;
        opacity: 0;
        visibility: hidden;
    }
    .dropdown .subs {
        transition: .35s;
        position: relative;
        width: 100%;
        border-right: none !important;
        border-left: none !important;
        padding: 5px !important;
        text-align: right;
    }
    .dropdown .subs:hover {

    }
    .dropdown .subs a {
        padding-right: .5rem;
        padding-right: .5rem;
        width: 100%;
        display: block;
        color: #666;
        text-align: right;
    }
    .dropdown .subs a:hover {
        text-decoration: none;
        color: #e65540;
        cursor: pointer;
    }
    
    .dropdown .subs .dropdown {
        position: absolute;
        right: 100%;
        top: 0;
        background: #fff;
        opacity: 0;
        visibility: hidden;
    }
    .dropdown .subs:hover .dropdown {
        opacity: 1;
        visibility: visible;
    }
    .mainnav > li {
        height: 100%;
        text-align: center;
        position: relative;
    }

        .mainnav > li:last-child {
            border: none;
        }

        .mainnav > li > a {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100%;
            padding: 0 3.5rem;
            color: white;
            font-family: IRANSans !important;
            color: #fff;
        }


</style>


<div class="main">
    <span class="nav-item-hover"></span>
    <ul class="mainnav">
        <li class="hassubs">
            <a href="~/Home/Index">صفحه اصلی</a>
        </li>
        <li class="hassubs">
            <a href="#">محصولات</a>
            <ul class="dropdown">
                @foreach (var item in productTypes.Where(p => p.ParentId == null))
                {
                    <li class="subs hassubs">
                        @if (productTypes.Any(p => p.ParentId.HasValue && p.ParentId.Value == item.Id))
                        {
                            <a>@item.Title</a>
                            <ul class="dropdown">
                                @foreach (var item2 in productTypes.Where(p => p.ParentId.HasValue && p.ParentId.Value == item.Id))
                                {
                                    <li class="subs"><a asp-action="Index" asp-controller="product" asp-route-ProductTypeId="@item2.Id">@item2.Title</a></li>
                                }
                            </ul>

                        }
                        else
                        {

                            <a asp-action="Index" asp-controller="product" asp-route-ProductTypeId="@item.Id">@item.Title</a>

                        }
                    </li>
                }
            </ul>
        </li>

        <li class="hassubs">
            <a href="~/Home/about">درباره ما</a>
        </li>

        @*<li class="hassubs">
            <a href="~/Home/About">مقالات</a>
        </li>*@
        <li class="hassubs">
            <a href="~/ContactUs/Index">ارتباط با ما</a>
        </li>


    </ul>
</div>









 