App.Admin/Controllers/Products/ProductColorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Alamut.Data.Structure;
using App.Common.Extentions;
using App.Common.Toolkit;
using App.Data.Sql.Context;
using App.DomainModels.Dto.Product;
using App.DomainModels.Entities.Models;
using App.DomainModels.ViewModels;
using App.DomainModels.ViewModels.Product;
using App.DomainServices.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace App.Admin.Controllers
{
    [Authorize]
    public class ProductColorController : Controller
    {
        private readonly ProductColorRepository _productColorRepository;
        public ProductColorController
            (ProductColorRepository productColorRepository)

        {
            _productColorRepository = productColorRepository;
        }

        public IActionResult Index(int ProductId)
        {
            ViewBag.productId = ProductId;
           var model= _productColorRepository.GetAll(ProductId);
            return View(model);
        }
         

        [HttpPost]
        public IActionResult Create(ProductColorSummaryDTO model)
        {
            var result = _productColorRepository.Create(model);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Index),new { ProductId=model.ProductId });
        }

        public IActionResult Edit(int Id)
        {
            var model = _productColorRepository.GetById(Id);
            if (model==null)
            {
                TempData.AddResult(ServiceResult.Error("نوعی یافت نشد!"));
                return View(nameof(Index), new { ProductId = model.ProductId });
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(ProductColorEditViewModel model,int Id)
        {
            var result = _productColorRepository.Edit(model,Id);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Edit),new { Id });
        }

   
        public IActionResult Delete(int Id)
        {
            var result = _productColorRepository.Delete(Id);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Index), new { ProductId = result.Data });
        }
    }
}

App.Admin/Controllers/Products/ProductGalleryImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Alamut.Data.Structure;
using App.Admin.Helpers;
using App.Common.Extentions;
using App.Data.Sql.Context;
using App.DomainModels.Dto.Product;
using App.DomainModels.Entities.Models;
using App.DomainModels.SSOT;
using App.DomainModels.ViewModels.Product;
using App.DomainServices.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace App.Admin.Controllers
{
    [Authorize]
    public class ProductGalleryImageController : Controller
    {
        private readonly ProductGalleryImageRepository _productGalleryImageRepository;
        private readonly FileConfig _fileConfig;
        private readonly IHostingEnvironment _environment;

        public ProductGalleryImageController(ProductGalleryImageRepository productGalleryImageRepository
            , IHostingEnvironment environment
            , FileConfig fileConfig)
        {
            _fileConfig = fileConfig;
            _environment = environment;
            _productGalleryImageRepository = productGalleryImageRepository;
        }

        public IActionResult Index(int ProductId)
        {
            ViewBag.ProductId = ProductId;
            var model = _productGalleryImageRepository.GetAll(ProductId);
            return View(model);
        }

        public IActionResult Create(int ProductId)
        {
            ViewBag.ProductId = ProductId;
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProductGalleryImageDTO model, IFormFile Image)
        {
            var imageName = FileHelper.SaveFile(Image, _fileConfig, FileType.Image, _environment.WebRootPath);
            if (imageName != null)
                model.Image = imageName;
            var result = _productGalleryImageRepository.Create(model);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Index), new { model.ProductId });
        }
         
        public IActionResult Delete(int Id, string ImagePath)
        {
            var result = _productGalleryImageRepository.Delete(Id);
            if (result.Succeed)
                //FileHelper.DeleteFile(ImagePath, _fileConfig, FileType.Image, _environment.WebRootPath);

            TempData.AddResult(result);
            return RedirectToAction(nameof(Index), new { result.Data });
        }

    }
}

App.Admin/Controllers/Products/ProductTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Alamut.Data.Structure;
using App.Common.Extentions;
using App.Common.Toolkit;
using App.Data.Sql.Context;
using App.DomainModels.Dto.Product;
using App.DomainModels.Entities.Models;
using App.DomainModels.ViewModels;
using App.DomainServices.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace App.Admin.Controllers
{
    [Authorize]
    public class ProductTypesController : Controller
    {
        private readonly ProductTypeRepository _productTypeRepository;
        public ProductTypesController
            (ProductTypeRepository productTypeRepository)

        {
            _productTypeRepository = productTypeRepository;
        }

        public IActionResult Index()
        {
           var model= _productTypeRepository.GetAll(null);
            return View(model);
        }
        
        public IActionResult SubGroup(int? parentId)
        {
            ViewBag.parentId = parentId;
            var model = _productTypeRepository.GetAll(parentId);
            return View(model);
        }

        public IActionResult Create(int? parentId)
        {
            ViewBag.parentId = parentId;
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProductTypeDTO model)
        {
            var result = _productTypeRepository.Create(model);
            TempData.AddResult(result);
            if (model.ParentId.HasValue)
            {
                return RedirectToAction(nameof(SubGroup), new { model.ParentId });
            }
            return RedirectToAction(nameof(Index));

        }

        public IActionResult Edit(int Id)
        {
            var model = _productTypeRepository.GetById(Id);
            if (model==null)
            {
                TempData.AddResult(ServiceResult.Error("نوعی یافت نشد!"));
                return View(nameof(Index));
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(ProductTypeEditViewModel model,int Id)
        {
            var result = _productTypeRepository.Edit(model,Id);
            TempData.AddResult(result); 

            if (model.ParentId.HasValue)
            {
                return RedirectToAction(nameof(SubGroup), new { model.ParentId });
            }
            return RedirectToAction(nameof(Index));
        }

   
        public IActionResult Delete(int Id)
        {
            var result = _productTypeRepository.Delete(Id);
            TempData.AddResult(result);
            if (result.Data.HasValue)
            {
                return RedirectToAction(nameof(SubGroup), new { result.Data });
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

App.Admin/Controllers/Products/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Alamut.Data.Structure;
using App.Admin.Helpers;
using App.Common.Extentions;
using App.DomainModels.Dto.Product;
using App.DomainModels.SSOT;
using App.DomainModels.ViewModels;
using App.DomainServices.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;

namespace App.Admin.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly ProductRepository _productRepository;
        private readonly ProductGalleryImageRepository _productGalleryImageRepository;
        private readonly ProductTypeRepository _productTypeRepository;
        private readonly FileConfig _fileConfig;
        private readonly IHostingEnvironment _environment;

        public ProductsController
            (ProductRepository productRepository
            , ProductGalleryImageRepository productGalleryImageRepository
            , FileConfig fileConfig
            , IHostingEnvironment environment
            , ProductTypeRepository productTypeRepository)

        {
            _productGalleryImageRepository = productGalleryImageRepository;
            _productRepository = productRepository;
            _fileConfig = fileConfig;
            _environment = environment;
            _productTypeRepository = productTypeRepository;
        }

        public IActionResult Index()
        {
            var model = _productRepository.GetAll();
            return View(model);
        }

        public IActionResult Create()
        {
            var ProductTypes = _productTypeRepository.GetList().Select(x => new { x.Id, Value = x.Title });

            ViewBag.ProductTypes = new SelectList(ProductTypes, "Id", "Value");

            return View();
        }

        [HttpPost]
        public IActionResult Create(ProductDTO model, IFormFile Image)
        {
            var imageName = FileHelper.SaveFile(Image, _fileConfig, FileType.Image, _environment.WebRootPath);
            if (imageName != null)
                model.Image = imageName;
            var result = _productRepository.Create(model);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int Id)
        {
            var model = _productRepository.GetById(Id);
            if (model == null)
            {
                TempData.AddResult(ServiceResult.Error("نوعی یافت نشد!"));
                return View(nameof(Index));
            }
            var ProductTypes = _productTypeRepository.GetList().Select(x => new { x.Id, Value = x.Title });

            ViewBag.ProductTypes = new SelectList(ProductTypes, "Id", "Value");

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(ProductEditViewModel model, int Id, IFormFile NewImage)
        {
            if (NewImage != null)
            {
                var imageName = FileHelper.SaveFile(NewImage, _fileConfig, FileType.Image, _environment.WebRootPath);
                FileHelper.DeleteFile(model.Image, _fileConfig, FileType.Image, _environment.WebRootPath);
                model.Image = imageName;
            }

            var result = _productRepository.Edit(model, Id);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Edit), new { Id });
        }


        public IActionResult Delete(int Id, string ImagePath)
        {
            var result = _productRepository.Delete(Id);
            if (result.Succeed)
            { 
                _productGalleryImageRepository.DeleteByProductId(Id); 
            }

            TempData.AddResult(result);
            return RedirectToAction(nameof(Index));
        }
    }
}

App.Admin/Views/Products/Create.cshtml
@using App.DomainModels.Dto.Product
@model ProductDTO
@using App.Regate
@using App.Common.Toolkit
@{
    ViewData["Title"] = "افزودن محصول";
}

@using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="container">

        <div class="row">

            <div class="col-lg-2 col-xs-12 col-sm-4">
                <div class="form-group">
                    <input type="text" asp-for="Name" required class="form-control form-control-sm" placeholder="نام محصول ">
                    <i class="form-group__bar"></i>
                </div>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="form-element form-select">
                    @Html.DropDownList("ProductTypeId", (IEnumerable<SelectListItem>)ViewBag.ProductTypes, "نوع محصول را انتخاب کنید", new { @class = "form-control" })
                </div>
            </div>
 
            <div class="col-md-6 col-xs-12 col-sm-4">
                <div class="col-lg-4 control-label">عکس اصلی محصول</div>
                <div class="col-lg-8">
                    <input type="file" name="Image" class="form-control form-control-sm" placeholder="عکس اصلی محصول ">

                </div>
            </div>


            <div class="col-md-12 col-xs-12 col-sm-4">
                <div class="form-group">
                    <label for="Description">توضیحات</label>

                    <textarea class="form-control form-control-lg" asp-for="Description" rows="8" placeholder="توضیحات را وارد کنید "></textarea>
                    <i class="form-group__bar"></i>
                </div>
            </div>


            <div class="col-md-12 col-xs-12 col-sm-4">
                <div class="form-group">
                    <label for="ShortDescription">توضیحات مختصر</label>

                    <textarea class="form-control form-control-lg" asp-for="ShortDescription" rows="8" placeholder="توضیحات مختصر را وارد کنید "></textarea>
                    <i class="form-group__bar"></i>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" style="float:left" class="btn btn-lg btn-outline-success">ایجاد</button>
            </div>
        </div>
    </div>
}

    <script>
        CKEDITOR.replace( 'ShortDescription' );
        CKEDITOR.replace( 'Description' );
    </script>

App.Admin/Views/Products/Edit.cshtml
@using App.DomainModels.Dto.Product
@model ProductDTO
@using App.Common.Toolkit
@using App.DomainModels.SSOT
@inject FileConfig config 
@{
    ViewData["Title"] = "ویرایش مصول";
}

@using (Html.BeginForm("Edit", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="Image" />
    <div class="container">

        <div class="row">

            <div class="col-lg-2 col-xs-12 col-sm-4">
                <div class="form-group">
                    <input type="text" asp-for="Name" required class="form-control form-control-sm" placeholder="نام محصول ">
                    <i class="form-group__bar"></i>
                </div>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="form-element form-select">
                    @Html.DropDownList("ProductTypeId", (IEnumerable<SelectListItem>)ViewBag.ProductTypes, "نوع محصول را انتخاب کنید", new { @class = "form-control" })
                </div>
            </div>

            <div class="col-md-6 col-xs-12 col-sm-4">
                <div class="col-lg-4 control-label">عکس اصلی محصول</div>
                <div class="col-lg-8">
                    <input type="file" name="NewImage" value="@Model.Image" class="form-control form-control-sm" placeholder="عکس اصلی محصول ">
                    @if (Model.Image != null)
                    { 
                        <img style="height:100px;width:100px" src="@Url.Content("~/UploadFiles")/@Model.Image">
 
                    }
                </div>
            </div>
            <div class="col-md-12 col-xs-12 col-sm-4">
                <div class="form-group">
                    <label for="Description">توضیحات </label>
                    <textarea class="form-control form-control-lg" asp-for="Description" rows="8" placeholder="توضیحات را وارد کنید "></textarea>
                    <i class="form-group__bar"></i>
                </div>
            </div>


            <div class="col-md-12 col-xs-12 col-sm-4">
                <div class="form-group">
                    <label for="ShortDescription">توضیحات مختصر</label>
                    <textarea class="form-control form-control-lg" style="direction:rtl" asp-for="ShortDescription" rows="8" placeholder="توضیحات مختصر را وارد کنید "></textarea>
                    <i class="form-group__bar"></i>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" style="float:left" class="btn btn-lg btn-outline-warning">ویرایش</button>
            </div>
        </div>
    </div>
}
   <script>
        CKEDITOR.replace( 'ShortDescription' );
        CKEDITOR.replace( 'Description' );
    </script>

App.Admin/Views/Products/Index.cshtml
@using App.DomainModels.Dto.Product
@model IEnumerable<ProductDTO>
@using App.DomainModels.SSOT
@inject FileConfig config

@{
    ViewData["Title"] = "انواع محصولات";
}
@{
    int counter = 0;
}
<div class="content__inner">
    <div class="row">
        <div class="col-md-12">
            <div class="content__inner__card wow zoomIn">
                <div class="content__inner__card__title">
                    محصولات
                </div>
                <br />

                <hr /> 
                <a style="margin:30px 0px" asp-action="Create" asp-controller="Products" class="btn btn-outline-warning">ایجاد محصول</a>
 

                <div class="table-responsive">
                    <table class="table  table-striped">
                        <thead>
                            <tr>
                                <th>ردیف</th>
                                <th>نام محصول</th>
                                <th>نوع محصول</th>
                                <th>تصویر اصلی محصول</th>
                                <th>توضیح مختصر</th>
                                <th>گالری</th>
                                <th>اقدامات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@(++counter)</td>
                                <td>@item.Name</td>
                                <td>@item.ProductType.Title</td>
                                <td>
                                <img src="@Url.Content("~/UploadFiles")/@item.Image" width="100" height="100" />
                                 <td>@item.ShortDescription</td>
                                 <td>
                                     <div class="form-group">
                                         <a asp-action="Index" asp-controller="ProductGalleryImage" asp-route-ProductId="@item.Id" class="btn btn-lg btn-outline-info">مدیریت گالری</a>
                                     </div>
                                     <div class="form-group">
                                         <a asp-action="Index" asp-controller="ProductColor" asp-route-ProductId="@item.Id" class="btn btn-lg btn-outline-warning">مدیریت رنگ</a>
                                     </div>
                                 </td>
                                <td>
                                    <a  asp-action="Edit" asp-controller="Products" asp-route-Id="@item.Id" class="action">
                                        <i class="pe-7s-edit"></i>
                                    </a>
                                    <a asp-action="Delete" asp-controller="Products" asp-route-Id="@item.Id"  asp-route-ImagePath="@item.Image" class="action">
                                        <i class="pe-7s-trash"></i>
                                    </a>
                                </td>

                            </tr>
                            }
                        </tbody>
                    </table>
                </div>

                @*<div class="text-center font-size-12 margin-top-20">
            نمایش 1 تا 2 از 17 مورد
        </div>

        <div class="pagination">
            <a class="pagination__btn"><i class="pe-7s-angle-left"></i></a>
            <a href="#" class="pagination__btn active">1</a>
            <a href="#" class="pagination__btn">2</a>
            <a href="#" class="pagination__btn">3</a>
            <a href="#" class="pagination__btn">4</a>
            <a class="pagination__btn disabled"><i class="pe-7s-angle-right"></i></a>
        </div>*@

            </div>
        </div>
    </div>
</div>